# Generated by Django 5.2.7 on 2025-11-03 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('file_path', models.CharField(max_length=300)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
